title: David Bunce
description: baptist pastor and theologian in Vienna, Austria

url: https://davidbunce.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
  - title: Journal Scribblings
    url: /index.html
  - title: About David
    url: /about
  - title: Academic
    url: /academic

social:
  github: davidbunce
  twitter: davidbunce
  facebook: david.bunce
  email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
